/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicLayoutImport } from './routes/_public-layout'
import { Route as ProtectedLayoutImport } from './routes/_protected-layout'
import { Route as ProtectedLayoutIndexImport } from './routes/_protected-layout/index'
import { Route as PublicLayoutLoginImport } from './routes/_public-layout/login'
import { Route as ProtectedLayoutMembersRouteImport } from './routes/_protected-layout/members/route'
import { Route as ProtectedLayoutAttendancesRouteImport } from './routes/_protected-layout/attendances/route'
import { Route as ProtectedLayoutMembersIndexImport } from './routes/_protected-layout/members/index'
import { Route as ProtectedLayoutAttendancesIndexImport } from './routes/_protected-layout/attendances/index'
import { Route as PublicLayoutMembersMemberIdImport } from './routes/_public-layout/members/$memberId'
import { Route as ProtectedLayoutMembersPresentImport } from './routes/_protected-layout/members/present'
import { Route as ProtectedLayoutMembersLateImport } from './routes/_protected-layout/members/late'

// Create/Update Routes

const PublicLayoutRoute = PublicLayoutImport.update({
  id: '/_public-layout',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedLayoutRoute = ProtectedLayoutImport.update({
  id: '/_protected-layout',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedLayoutIndexRoute = ProtectedLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const PublicLayoutLoginRoute = PublicLayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => PublicLayoutRoute,
} as any)

const ProtectedLayoutMembersRouteRoute =
  ProtectedLayoutMembersRouteImport.update({
    path: '/members',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

const ProtectedLayoutAttendancesRouteRoute =
  ProtectedLayoutAttendancesRouteImport.update({
    path: '/attendances',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

const ProtectedLayoutMembersIndexRoute =
  ProtectedLayoutMembersIndexImport.update({
    path: '/',
    getParentRoute: () => ProtectedLayoutMembersRouteRoute,
  } as any)

const ProtectedLayoutAttendancesIndexRoute =
  ProtectedLayoutAttendancesIndexImport.update({
    path: '/',
    getParentRoute: () => ProtectedLayoutAttendancesRouteRoute,
  } as any)

const PublicLayoutMembersMemberIdRoute =
  PublicLayoutMembersMemberIdImport.update({
    path: '/members/$memberId',
    getParentRoute: () => PublicLayoutRoute,
  } as any)

const ProtectedLayoutMembersPresentRoute =
  ProtectedLayoutMembersPresentImport.update({
    path: '/present',
    getParentRoute: () => ProtectedLayoutMembersRouteRoute,
  } as any)

const ProtectedLayoutMembersLateRoute = ProtectedLayoutMembersLateImport.update(
  {
    path: '/late',
    getParentRoute: () => ProtectedLayoutMembersRouteRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected-layout': {
      id: '/_protected-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_public-layout': {
      id: '/_public-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_protected-layout/attendances': {
      id: '/_protected-layout/attendances'
      path: '/attendances'
      fullPath: '/attendances'
      preLoaderRoute: typeof ProtectedLayoutAttendancesRouteImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected-layout/members': {
      id: '/_protected-layout/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof ProtectedLayoutMembersRouteImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_public-layout/login': {
      id: '/_public-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLayoutLoginImport
      parentRoute: typeof PublicLayoutImport
    }
    '/_protected-layout/': {
      id: '/_protected-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutIndexImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected-layout/members/late': {
      id: '/_protected-layout/members/late'
      path: '/late'
      fullPath: '/members/late'
      preLoaderRoute: typeof ProtectedLayoutMembersLateImport
      parentRoute: typeof ProtectedLayoutMembersRouteImport
    }
    '/_protected-layout/members/present': {
      id: '/_protected-layout/members/present'
      path: '/present'
      fullPath: '/members/present'
      preLoaderRoute: typeof ProtectedLayoutMembersPresentImport
      parentRoute: typeof ProtectedLayoutMembersRouteImport
    }
    '/_public-layout/members/$memberId': {
      id: '/_public-layout/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof PublicLayoutMembersMemberIdImport
      parentRoute: typeof PublicLayoutImport
    }
    '/_protected-layout/attendances/': {
      id: '/_protected-layout/attendances/'
      path: '/'
      fullPath: '/attendances/'
      preLoaderRoute: typeof ProtectedLayoutAttendancesIndexImport
      parentRoute: typeof ProtectedLayoutAttendancesRouteImport
    }
    '/_protected-layout/members/': {
      id: '/_protected-layout/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof ProtectedLayoutMembersIndexImport
      parentRoute: typeof ProtectedLayoutMembersRouteImport
    }
  }
}

// Create and export the route tree

interface ProtectedLayoutAttendancesRouteRouteChildren {
  ProtectedLayoutAttendancesIndexRoute: typeof ProtectedLayoutAttendancesIndexRoute
}

const ProtectedLayoutAttendancesRouteRouteChildren: ProtectedLayoutAttendancesRouteRouteChildren =
  {
    ProtectedLayoutAttendancesIndexRoute: ProtectedLayoutAttendancesIndexRoute,
  }

const ProtectedLayoutAttendancesRouteRouteWithChildren =
  ProtectedLayoutAttendancesRouteRoute._addFileChildren(
    ProtectedLayoutAttendancesRouteRouteChildren,
  )

interface ProtectedLayoutMembersRouteRouteChildren {
  ProtectedLayoutMembersLateRoute: typeof ProtectedLayoutMembersLateRoute
  ProtectedLayoutMembersPresentRoute: typeof ProtectedLayoutMembersPresentRoute
  ProtectedLayoutMembersIndexRoute: typeof ProtectedLayoutMembersIndexRoute
}

const ProtectedLayoutMembersRouteRouteChildren: ProtectedLayoutMembersRouteRouteChildren =
  {
    ProtectedLayoutMembersLateRoute: ProtectedLayoutMembersLateRoute,
    ProtectedLayoutMembersPresentRoute: ProtectedLayoutMembersPresentRoute,
    ProtectedLayoutMembersIndexRoute: ProtectedLayoutMembersIndexRoute,
  }

const ProtectedLayoutMembersRouteRouteWithChildren =
  ProtectedLayoutMembersRouteRoute._addFileChildren(
    ProtectedLayoutMembersRouteRouteChildren,
  )

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutAttendancesRouteRoute: typeof ProtectedLayoutAttendancesRouteRouteWithChildren
  ProtectedLayoutMembersRouteRoute: typeof ProtectedLayoutMembersRouteRouteWithChildren
  ProtectedLayoutIndexRoute: typeof ProtectedLayoutIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutAttendancesRouteRoute:
    ProtectedLayoutAttendancesRouteRouteWithChildren,
  ProtectedLayoutMembersRouteRoute:
    ProtectedLayoutMembersRouteRouteWithChildren,
  ProtectedLayoutIndexRoute: ProtectedLayoutIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicLayoutLoginRoute: typeof PublicLayoutLoginRoute
  PublicLayoutMembersMemberIdRoute: typeof PublicLayoutMembersMemberIdRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutLoginRoute: PublicLayoutLoginRoute,
  PublicLayoutMembersMemberIdRoute: PublicLayoutMembersMemberIdRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof PublicLayoutRouteWithChildren
  '/attendances': typeof ProtectedLayoutAttendancesRouteRouteWithChildren
  '/members': typeof ProtectedLayoutMembersRouteRouteWithChildren
  '/login': typeof PublicLayoutLoginRoute
  '/': typeof ProtectedLayoutIndexRoute
  '/members/late': typeof ProtectedLayoutMembersLateRoute
  '/members/present': typeof ProtectedLayoutMembersPresentRoute
  '/members/$memberId': typeof PublicLayoutMembersMemberIdRoute
  '/attendances/': typeof ProtectedLayoutAttendancesIndexRoute
  '/members/': typeof ProtectedLayoutMembersIndexRoute
}

export interface FileRoutesByTo {
  '': typeof PublicLayoutRouteWithChildren
  '/login': typeof PublicLayoutLoginRoute
  '/': typeof ProtectedLayoutIndexRoute
  '/members/late': typeof ProtectedLayoutMembersLateRoute
  '/members/present': typeof ProtectedLayoutMembersPresentRoute
  '/members/$memberId': typeof PublicLayoutMembersMemberIdRoute
  '/attendances': typeof ProtectedLayoutAttendancesIndexRoute
  '/members': typeof ProtectedLayoutMembersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_protected-layout': typeof ProtectedLayoutRouteWithChildren
  '/_public-layout': typeof PublicLayoutRouteWithChildren
  '/_protected-layout/attendances': typeof ProtectedLayoutAttendancesRouteRouteWithChildren
  '/_protected-layout/members': typeof ProtectedLayoutMembersRouteRouteWithChildren
  '/_public-layout/login': typeof PublicLayoutLoginRoute
  '/_protected-layout/': typeof ProtectedLayoutIndexRoute
  '/_protected-layout/members/late': typeof ProtectedLayoutMembersLateRoute
  '/_protected-layout/members/present': typeof ProtectedLayoutMembersPresentRoute
  '/_public-layout/members/$memberId': typeof PublicLayoutMembersMemberIdRoute
  '/_protected-layout/attendances/': typeof ProtectedLayoutAttendancesIndexRoute
  '/_protected-layout/members/': typeof ProtectedLayoutMembersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/attendances'
    | '/members'
    | '/login'
    | '/'
    | '/members/late'
    | '/members/present'
    | '/members/$memberId'
    | '/attendances/'
    | '/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/'
    | '/members/late'
    | '/members/present'
    | '/members/$memberId'
    | '/attendances'
    | '/members'
  id:
    | '__root__'
    | '/_protected-layout'
    | '/_public-layout'
    | '/_protected-layout/attendances'
    | '/_protected-layout/members'
    | '/_public-layout/login'
    | '/_protected-layout/'
    | '/_protected-layout/members/late'
    | '/_protected-layout/members/present'
    | '/_public-layout/members/$memberId'
    | '/_protected-layout/attendances/'
    | '/_protected-layout/members/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protected-layout",
        "/_public-layout"
      ]
    },
    "/_protected-layout": {
      "filePath": "_protected-layout.tsx",
      "children": [
        "/_protected-layout/attendances",
        "/_protected-layout/members",
        "/_protected-layout/"
      ]
    },
    "/_public-layout": {
      "filePath": "_public-layout.tsx",
      "children": [
        "/_public-layout/login",
        "/_public-layout/members/$memberId"
      ]
    },
    "/_protected-layout/attendances": {
      "filePath": "_protected-layout/attendances/route.tsx",
      "parent": "/_protected-layout",
      "children": [
        "/_protected-layout/attendances/"
      ]
    },
    "/_protected-layout/members": {
      "filePath": "_protected-layout/members/route.tsx",
      "parent": "/_protected-layout",
      "children": [
        "/_protected-layout/members/late",
        "/_protected-layout/members/present",
        "/_protected-layout/members/"
      ]
    },
    "/_public-layout/login": {
      "filePath": "_public-layout/login.tsx",
      "parent": "/_public-layout"
    },
    "/_protected-layout/": {
      "filePath": "_protected-layout/index.tsx",
      "parent": "/_protected-layout"
    },
    "/_protected-layout/members/late": {
      "filePath": "_protected-layout/members/late.tsx",
      "parent": "/_protected-layout/members"
    },
    "/_protected-layout/members/present": {
      "filePath": "_protected-layout/members/present.tsx",
      "parent": "/_protected-layout/members"
    },
    "/_public-layout/members/$memberId": {
      "filePath": "_public-layout/members/$memberId.tsx",
      "parent": "/_public-layout"
    },
    "/_protected-layout/attendances/": {
      "filePath": "_protected-layout/attendances/index.tsx",
      "parent": "/_protected-layout/attendances"
    },
    "/_protected-layout/members/": {
      "filePath": "_protected-layout/members/index.tsx",
      "parent": "/_protected-layout/members"
    }
  }
}
ROUTE_MANIFEST_END */
