/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MembersRouteImport } from './routes/members/route'
import { Route as AttendancesRouteImport } from './routes/attendances/route'
import { Route as MembersIndexImport } from './routes/members/index'
import { Route as AttendancesIndexImport } from './routes/attendances/index'
import { Route as MembersPresentImport } from './routes/members/present'
import { Route as MembersLateImport } from './routes/members/late'

// Create/Update Routes

const MembersRouteRoute = MembersRouteImport.update({
  path: '/members',
  getParentRoute: () => rootRoute,
} as any)

const AttendancesRouteRoute = AttendancesRouteImport.update({
  path: '/attendances',
  getParentRoute: () => rootRoute,
} as any)

const MembersIndexRoute = MembersIndexImport.update({
  path: '/',
  getParentRoute: () => MembersRouteRoute,
} as any)

const AttendancesIndexRoute = AttendancesIndexImport.update({
  path: '/',
  getParentRoute: () => AttendancesRouteRoute,
} as any)

const MembersPresentRoute = MembersPresentImport.update({
  path: '/present',
  getParentRoute: () => MembersRouteRoute,
} as any)

const MembersLateRoute = MembersLateImport.update({
  path: '/late',
  getParentRoute: () => MembersRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/attendances': {
      id: '/attendances'
      path: '/attendances'
      fullPath: '/attendances'
      preLoaderRoute: typeof AttendancesRouteImport
      parentRoute: typeof rootRoute
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRoute
    }
    '/members/late': {
      id: '/members/late'
      path: '/late'
      fullPath: '/members/late'
      preLoaderRoute: typeof MembersLateImport
      parentRoute: typeof MembersRouteImport
    }
    '/members/present': {
      id: '/members/present'
      path: '/present'
      fullPath: '/members/present'
      preLoaderRoute: typeof MembersPresentImport
      parentRoute: typeof MembersRouteImport
    }
    '/attendances/': {
      id: '/attendances/'
      path: '/'
      fullPath: '/attendances/'
      preLoaderRoute: typeof AttendancesIndexImport
      parentRoute: typeof AttendancesRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexImport
      parentRoute: typeof MembersRouteImport
    }
  }
}

// Create and export the route tree

interface AttendancesRouteRouteChildren {
  AttendancesIndexRoute: typeof AttendancesIndexRoute
}

const AttendancesRouteRouteChildren: AttendancesRouteRouteChildren = {
  AttendancesIndexRoute: AttendancesIndexRoute,
}

const AttendancesRouteRouteWithChildren =
  AttendancesRouteRoute._addFileChildren(AttendancesRouteRouteChildren)

interface MembersRouteRouteChildren {
  MembersLateRoute: typeof MembersLateRoute
  MembersPresentRoute: typeof MembersPresentRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

const MembersRouteRouteChildren: MembersRouteRouteChildren = {
  MembersLateRoute: MembersLateRoute,
  MembersPresentRoute: MembersPresentRoute,
  MembersIndexRoute: MembersIndexRoute,
}

const MembersRouteRouteWithChildren = MembersRouteRoute._addFileChildren(
  MembersRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/attendances': typeof AttendancesRouteRouteWithChildren
  '/members': typeof MembersRouteRouteWithChildren
  '/members/late': typeof MembersLateRoute
  '/members/present': typeof MembersPresentRoute
  '/attendances/': typeof AttendancesIndexRoute
  '/members/': typeof MembersIndexRoute
}

export interface FileRoutesByTo {
  '/members/late': typeof MembersLateRoute
  '/members/present': typeof MembersPresentRoute
  '/attendances': typeof AttendancesIndexRoute
  '/members': typeof MembersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/attendances': typeof AttendancesRouteRouteWithChildren
  '/members': typeof MembersRouteRouteWithChildren
  '/members/late': typeof MembersLateRoute
  '/members/present': typeof MembersPresentRoute
  '/attendances/': typeof AttendancesIndexRoute
  '/members/': typeof MembersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/attendances'
    | '/members'
    | '/members/late'
    | '/members/present'
    | '/attendances/'
    | '/members/'
  fileRoutesByTo: FileRoutesByTo
  to: '/members/late' | '/members/present' | '/attendances' | '/members'
  id:
    | '__root__'
    | '/attendances'
    | '/members'
    | '/members/late'
    | '/members/present'
    | '/attendances/'
    | '/members/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AttendancesRouteRoute: typeof AttendancesRouteRouteWithChildren
  MembersRouteRoute: typeof MembersRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AttendancesRouteRoute: AttendancesRouteRouteWithChildren,
  MembersRouteRoute: MembersRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/attendances",
        "/members"
      ]
    },
    "/attendances": {
      "filePath": "attendances/route.tsx",
      "children": [
        "/attendances/"
      ]
    },
    "/members": {
      "filePath": "members/route.tsx",
      "children": [
        "/members/late",
        "/members/present",
        "/members/"
      ]
    },
    "/members/late": {
      "filePath": "members/late.tsx",
      "parent": "/members"
    },
    "/members/present": {
      "filePath": "members/present.tsx",
      "parent": "/members"
    },
    "/attendances/": {
      "filePath": "attendances/index.tsx",
      "parent": "/attendances"
    },
    "/members/": {
      "filePath": "members/index.tsx",
      "parent": "/members"
    }
  }
}
ROUTE_MANIFEST_END */
