/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MembersRouteImport } from './routes/members/route'
import { Route as AttendancesRouteImport } from './routes/attendances/route'
import { Route as AttendancesIndexImport } from './routes/attendances/index'

// Create/Update Routes

const MembersRouteRoute = MembersRouteImport.update({
  path: '/members',
  getParentRoute: () => rootRoute,
} as any)

const AttendancesRouteRoute = AttendancesRouteImport.update({
  path: '/attendances',
  getParentRoute: () => rootRoute,
} as any)

const AttendancesIndexRoute = AttendancesIndexImport.update({
  path: '/',
  getParentRoute: () => AttendancesRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/attendances': {
      id: '/attendances'
      path: '/attendances'
      fullPath: '/attendances'
      preLoaderRoute: typeof AttendancesRouteImport
      parentRoute: typeof rootRoute
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRoute
    }
    '/attendances/': {
      id: '/attendances/'
      path: '/'
      fullPath: '/attendances/'
      preLoaderRoute: typeof AttendancesIndexImport
      parentRoute: typeof AttendancesRouteImport
    }
  }
}

// Create and export the route tree

interface AttendancesRouteRouteChildren {
  AttendancesIndexRoute: typeof AttendancesIndexRoute
}

const AttendancesRouteRouteChildren: AttendancesRouteRouteChildren = {
  AttendancesIndexRoute: AttendancesIndexRoute,
}

const AttendancesRouteRouteWithChildren =
  AttendancesRouteRoute._addFileChildren(AttendancesRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/attendances': typeof AttendancesRouteRouteWithChildren
  '/members': typeof MembersRouteRoute
  '/attendances/': typeof AttendancesIndexRoute
}

export interface FileRoutesByTo {
  '/members': typeof MembersRouteRoute
  '/attendances': typeof AttendancesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/attendances': typeof AttendancesRouteRouteWithChildren
  '/members': typeof MembersRouteRoute
  '/attendances/': typeof AttendancesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/attendances' | '/members' | '/attendances/'
  fileRoutesByTo: FileRoutesByTo
  to: '/members' | '/attendances'
  id: '__root__' | '/attendances' | '/members' | '/attendances/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AttendancesRouteRoute: typeof AttendancesRouteRouteWithChildren
  MembersRouteRoute: typeof MembersRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  AttendancesRouteRoute: AttendancesRouteRouteWithChildren,
  MembersRouteRoute: MembersRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/attendances",
        "/members"
      ]
    },
    "/attendances": {
      "filePath": "attendances/route.tsx",
      "children": [
        "/attendances/"
      ]
    },
    "/members": {
      "filePath": "members/route.tsx"
    },
    "/attendances/": {
      "filePath": "attendances/index.tsx",
      "parent": "/attendances"
    }
  }
}
ROUTE_MANIFEST_END */
